import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { initProject, inspectReceipt, sealReceipt } from "../dist/index.js";
function runCli(args,cwd){return spawnSync(process.execPath,[join(process.cwd(),"bin/vibeproof.mjs"),...args],{cwd,encoding:"utf8"});}
function git(cwd,...args){const r=spawnSync("git",args,{cwd,encoding:"utf8"});if(r.status!==0)throw new Error(r.stderr);}
test("initProject generates conservative contract, gitignore, and refuses overwrite",async()=>{const root=await mkdtemp(join(tmpdir(),"vp-init-"));try{await writeFile(join(root,"package.json"),JSON.stringify({name:"demo",scripts:{build:"x",start:"x"}}));await writeFile(join(root,"package-lock.json"),'{"lockfileVersion":3,"packages":{}}');const first=await initProject(root);assert.equal(first.created,true);assert.equal(first.gitignoreUpdated,true);const config=JSON.parse(await readFile(first.path,"utf8"));assert.deepEqual(config.commands.install.argv,["npm","ci"]);assert.match(await readFile(join(root,".gitignore"),"utf8"),/\.vibeproof\//);assert.equal((await initProject(root)).reason,"exists");}finally{await rm(root,{recursive:true,force:true});}});
test("inspectReceipt validates hash",()=>{const receipt=sealReceipt({receiptVersion:1,runId:"x",projectName:"p",createdAt:"2026-01-01T00:00:00.000Z",source:{requested:"local:p",requestedRef:"a".repeat(40),commitSha:"a".repeat(40),cleanClone:true,projectRoot:"."},environment:{platform:"linux",architecture:"x64",nodeVersion:"v22"},stages:[],browser:{journey:[],afterRestart:[]},artifacts:[],claims:{sourceVerified:true,installPassed:null,buildPassed:null,runtimeReady:true,browserJourneyPassed:false,restartPassed:null,verified:true},result:{status:"verified",failedStage:null}});assert.equal(inspectReceipt(receipt).integrity,"valid");});
test("CLI version/help, init, doctor, and unknown option",async()=>{const root=await mkdtemp(join(tmpdir(),"vp-cli-"));try{assert.equal(runCli(["--version"],process.cwd()).stdout.trim(),"0.1.0");assert.match(runCli(["--help"],process.cwd()).stdout,/Usage/);await writeFile(join(root,"package.json"),JSON.stringify({name:"demo",scripts:{start:"node server.js"}}));await writeFile(join(root,"package-lock.json"),'{"lockfileVersion":3,"packages":{}}');git(root,"init","-b","main");git(root,"config","user.email","x@y.z");git(root,"config","user.name","X");git(root,"add",".");git(root,"commit","-m","initial");assert.equal(runCli(["init",root,"--json"],process.cwd()).status,0);git(root,"add","vibeproof.config.json",".gitignore");git(root,"commit","-m","proof config");const doctor=runCli(["doctor",root,"--json"],process.cwd());assert.equal(doctor.status,0);assert.equal(JSON.parse(doctor.stdout).ready,true);const bad=runCli(["doctor",root,"--wat"],process.cwd());assert.equal(bad.status,1);assert.match(bad.stderr,/VP_CLI_OPTION/);}finally{await rm(root,{recursive:true,force:true});}});
