import { spawn, spawnSync } from "node:child_process";
import { access, mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { constants } from "node:fs";
import { tmpdir } from "node:os";
import { basename, dirname, join } from "node:path";
import { CdpClient } from "./cdp.js";
import { findFreePort } from "./network.js";
import { VibeProofError } from "./errors.js";
import type { BrowserStep, BrowserStepResult } from "./types.js";
export interface RunBrowserJourneyOptions { readonly baseUrl: string; readonly steps: readonly BrowserStep[]; readonly screenshotsDirectory: string; readonly defaultTimeoutMs: number; readonly executable?: string }
export interface BrowserJourneyResult { readonly steps: readonly BrowserStepResult[]; readonly browserExecutable: string; readonly browserVersion: string }
interface Session { readonly executable: string; readonly product: string; readonly client: CdpClient; readonly sessionId: string; readonly child: any; readonly profile: string; close(): Promise<void> }
const CANDIDATES = [process.env.CHROME_PATH, "google-chrome-stable", "google-chrome", "chromium", "chromium-browser", "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", "/Applications/Chromium.app/Contents/MacOS/Chromium"].filter((value): value is string => typeof value === "string" && value.length > 0);
async function exists(candidate: string): Promise<boolean> { if (candidate.includes("/")) { try { await access(candidate, constants.X_OK); return true; } catch { return false; } } return spawnSync(candidate, ["--version"], { stdio: "ignore" }).status === 0; }
export async function findBrowserExecutable(preferred?: string): Promise<string> { for (const candidate of preferred === undefined ? CANDIDATES : [preferred, ...CANDIDATES.filter((item) => item !== preferred)]) if (await exists(candidate)) return candidate; throw new VibeProofError("VP_BROWSER_NOT_FOUND", "No Chromium-family browser was found. Set browser.executable or CHROME_PATH."); }
async function terminate(pid: number): Promise<void> { try { process.kill(process.platform === "win32" ? pid : -pid, "SIGTERM"); } catch {} await new Promise((r) => setTimeout(r, 300)); try { process.kill(process.platform === "win32" ? pid : -pid, "SIGKILL"); } catch {} }
async function pollVersion(port: number, child: any, stderr: () => string, timeoutMs: number): Promise<{ webSocketDebuggerUrl: string }> { const deadline = Date.now() + timeoutMs; while (Date.now() < deadline) { if (child.exitCode !== null) throw new VibeProofError("VP_BROWSER_START", `Chromium exited before CDP became ready. ${stderr().slice(-2000)}`); try { const response = await fetch(`http://127.0.0.1:${port}/json/version`, { signal: AbortSignal.timeout(500) }); if (response.ok) return await response.json() as { webSocketDebuggerUrl: string }; } catch {} await new Promise((r) => setTimeout(r, 60)); } throw new VibeProofError("VP_BROWSER_START", `Chromium CDP did not become ready. ${stderr().slice(-2000)}`); }
async function launchBrowser(preferred?: string): Promise<Session> {
  const executable = await findBrowserExecutable(preferred); const port = await findFreePort(); const profile = await mkdtemp(join(tmpdir(), "vibeproof-chrome-")); let stderr = "";
  const args = [`--remote-debugging-port=${port}`, `--user-data-dir=${profile}`, "--headless=new", "--no-first-run", "--no-default-browser-check", "--disable-background-networking", "--disable-component-update", "--disable-sync", "--metrics-recording-only", "--disable-extensions", "--window-size=1440,1000", "about:blank"];
  if (process.platform === "linux" && process.getuid?.() === 0) args.push("--no-sandbox");
  const child = spawn(executable, args, { shell: false, detached: true, stdio: ["ignore", "ignore", "pipe"] }); child.stderr?.setEncoding("utf8"); child.stderr?.on("data", (chunk: string) => { if (stderr.length < 20_000) stderr += chunk; }); const pid = child.pid; if (pid === undefined) throw new VibeProofError("VP_BROWSER_START", "Chromium did not expose a process ID.");
  try { const endpoint = await pollVersion(port, child, () => stderr, 12_000); const client = await CdpClient.connect(endpoint.webSocketDebuggerUrl); const version = await client.send<{ product: string }>("Browser.getVersion"); const target = await client.send<{ targetId: string }>("Target.createTarget", { url: "about:blank" }); const attached = await client.send<{ sessionId: string }>("Target.attachToTarget", { targetId: target.targetId, flatten: true }); await client.send("Page.enable", {}, attached.sessionId); await client.send("Runtime.enable", {}, attached.sessionId); return { executable, product: version.product, client, sessionId: attached.sessionId, child, profile, async close() { client.close(); await terminate(pid); await rm(profile, { recursive: true, force: true }); } }; } catch (error) { await terminate(pid); await rm(profile, { recursive: true, force: true }); throw error; }
}
async function evaluate<T>(session: Session, expression: string): Promise<T> { const response = await session.client.send<{ result?: { value?: T }; exceptionDetails?: { text?: string; exception?: { description?: string } } }>("Runtime.evaluate", { expression, returnByValue: true, awaitPromise: true, userGesture: true }, session.sessionId); if (response.exceptionDetails) throw new VibeProofError("VP_BROWSER_EVALUATE", response.exceptionDetails.exception?.description ?? response.exceptionDetails.text ?? "Browser evaluation failed."); return response.result?.value as T; }
async function waitUntil(session: Session, expression: string, timeoutMs: number, description: string): Promise<void> { const deadline = Date.now() + timeoutMs; while (Date.now() < deadline) { if (await evaluate<boolean>(session, expression)) return; await new Promise((r) => setTimeout(r, 50)); } throw new VibeProofError("VP_BROWSER_TIMEOUT", `Timed out waiting for ${description}.`); }
async function navigate(session: Session, url: string, timeoutMs: number): Promise<void> { const loaded = session.client.waitForEvent("Page.loadEventFired", session.sessionId, timeoutMs); const response = await session.client.send<{ errorText?: string }>("Page.navigate", { url }, session.sessionId); if (response.errorText) throw new VibeProofError("VP_BROWSER_NAVIGATE", `Navigation failed: ${response.errorText}.`); await loaded; }
function selector(selector: string): string { return `Boolean(document.querySelector(${JSON.stringify(selector)}))`; }
function text(value: string): string { return `(document.body?.innerText ?? "").includes(${JSON.stringify(value)})`; }
async function screenshot(session: Session, path: string, fullPage: boolean): Promise<void> { await mkdir(dirname(path), { recursive: true }); const params: Record<string, unknown> = { format: "png", captureBeyondViewport: true, fromSurface: true }; if (fullPage) { const metrics = await session.client.send<{ contentSize: { width: number; height: number } }>("Page.getLayoutMetrics", {}, session.sessionId); params.clip = { x: 0, y: 0, width: Math.max(1, metrics.contentSize.width), height: Math.max(1, metrics.contentSize.height), scale: 1 }; } const captured = await session.client.send<{ data: string }>("Page.captureScreenshot", params, session.sessionId); await writeFile(path, Buffer.from(captured.data, "base64")); }
async function execute(session: Session, step: BrowserStep, baseUrl: string, directory: string, timeout: number): Promise<string | undefined> {
  switch (step.op) {
    case "goto": { const url = new URL(step.path, baseUrl).href; await navigate(session, url, step.timeoutMs ?? timeout); return url; }
    case "waitForSelector": await waitUntil(session, selector(step.selector), step.timeoutMs ?? timeout, `selector ${step.selector}`); return step.selector;
    case "waitForText": await waitUntil(session, text(step.text), step.timeoutMs ?? timeout, `text ${step.text}`); return "text-present";
    case "assertText": if (!(await evaluate<boolean>(session, text(step.text)))) throw new VibeProofError("VP_BROWSER_ASSERT", "Expected page text was not found."); return "text-present";
    case "assertSelector": if (!(await evaluate<boolean>(session, selector(step.selector)))) throw new VibeProofError("VP_BROWSER_ASSERT", `Expected selector was not found: ${step.selector}.`); return step.selector;
    case "fill": { const result = await evaluate<{ ok: boolean; error?: string }>(session, `(() => { const element=document.querySelector(${JSON.stringify(step.selector)}); if(!element)return {ok:false,error:"missing selector"}; if(!("value" in element))return {ok:false,error:"element has no value"}; element.focus(); element.value=${JSON.stringify(step.value)}; element.dispatchEvent(new Event("input",{bubbles:true})); element.dispatchEvent(new Event("change",{bubbles:true})); return {ok:true}; })()`); if (!result.ok) throw new VibeProofError("VP_BROWSER_FILL", `Could not fill ${step.selector}: ${result.error ?? "unknown error"}.`); return step.selector; }
    case "click": { await waitUntil(session, selector(step.selector), step.timeoutMs ?? timeout, `selector ${step.selector}`); const result = await evaluate<{ ok: boolean; error?: string }>(session, `(() => { const element=document.querySelector(${JSON.stringify(step.selector)}); if(!element)return {ok:false,error:"missing selector"}; if(element.disabled)return {ok:false,error:"disabled"}; element.click(); return {ok:true}; })()`); if (!result.ok) throw new VibeProofError("VP_BROWSER_CLICK", `Could not click ${step.selector}: ${result.error ?? "unknown error"}.`); return step.selector; }
    case "assertUrl": { const current = await evaluate<string>(session, "location.href"); if (typeof step.value === "string") { const expected = new URL(step.value, baseUrl).href; if (current !== expected) throw new VibeProofError("VP_BROWSER_ASSERT", `Expected URL ${expected}, got ${current}.`); } else { let pattern: RegExp; try { pattern = new RegExp(step.value.pattern); } catch { throw new VibeProofError("VP_BROWSER_ASSERT", `Invalid URL pattern: ${step.value.pattern}.`); } if (!pattern.test(current)) throw new VibeProofError("VP_BROWSER_ASSERT", `URL ${current} did not match the required pattern.`); } return current; }
    case "screenshot": { const file = basename(step.name.endsWith(".png") ? step.name : `${step.name}.png`); await screenshot(session, join(directory, file), step.fullPage ?? true); return `screenshots/${file}`; }
  }
}
export async function runBrowserJourney(options: RunBrowserJourneyOptions): Promise<BrowserJourneyResult> { await mkdir(options.screenshotsDirectory, { recursive: true }); const session = await launchBrowser(options.executable); const results: BrowserStepResult[] = []; try { for (const [index, step] of options.steps.entries()) { const start = Date.now(); const startedAt = new Date(start).toISOString(); try { const evidence = await execute(session, step, options.baseUrl, options.screenshotsDirectory, options.defaultTimeoutMs); const finish = Date.now(); results.push({ index, op: step.op, status: "passed", startedAt, finishedAt: new Date(finish).toISOString(), durationMs: finish - start, ...(evidence === undefined ? {} : { evidence }) }); } catch (error) { const finish = Date.now(); const message = error instanceof Error ? error.message : String(error); results.push({ index, op: step.op, status: "failed", startedAt, finishedAt: new Date(finish).toISOString(), durationMs: finish - start, error: message }); try { await screenshot(session, join(options.screenshotsDirectory, "failure.png"), true); } catch {} throw new VibeProofError("VP_BROWSER_STEP", `Browser step ${index + 1} (${step.op}) failed: ${message}.`, { index, op: step.op, results }); } } return { steps: results, browserExecutable: session.executable, browserVersion: session.product }; } finally { await session.close(); } }
