import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { doctorProject } from "./doctor.js";
import { VibeProofError, asVibeProofError } from "./errors.js";
import { initProject } from "./init.js";
import { inspectReceipt } from "./receipt.js";
import { verifyProject } from "./verify.js";
export const VERSION = "0.1.0";
const HELP = `VibeProof ${VERSION}\n\nUsage:\n  vibeproof init [repo] [--config path] [--json]\n  vibeproof doctor [repo] [--config path] [--browser path] [--json]\n  vibeproof verify [repo] [--config path] [--output path] [--browser path] [--keep-workspace] [--json]\n  vibeproof inspect <receipt.json> [--json]\n  vibeproof --version\n  vibeproof --help\n\nExit codes:\n  0  proof verified or command succeeded\n  1  configuration or operational error\n  2  proof failed, doctor blocked, or receipt integrity invalid\n`;
interface Parsed { readonly positionals: string[]; readonly options: Map<string, string | true> }
const BOOLEAN = new Set(["--json", "--keep-workspace", "--help", "--version"]); const VALUES = new Set(["--config", "--output", "--browser"]);
function parse(args: readonly string[]): Parsed { const positionals: string[] = []; const options = new Map<string, string | true>(); for (let index = 0; index < args.length; index += 1) { const item = args[index]!; if (!item.startsWith("--")) { positionals.push(item); continue; } if (BOOLEAN.has(item)) { if (options.has(item)) throw new VibeProofError("VP_CLI_OPTION", `Option ${item} was provided more than once.`); options.set(item, true); continue; } if (!VALUES.has(item)) throw new VibeProofError("VP_CLI_OPTION", `Unknown option: ${item}.`); const next = args[index + 1]; if (next === undefined || next.startsWith("--")) throw new VibeProofError("VP_CLI_OPTION", `Option ${item} requires a value.`); if (options.has(item)) throw new VibeProofError("VP_CLI_OPTION", `Option ${item} was provided more than once.`); options.set(item, next); index += 1; } return { positionals, options }; }
function allow(parsed: Parsed, names: readonly string[]): void { for (const name of parsed.options.keys()) if (!names.includes(name)) throw new VibeProofError("VP_CLI_OPTION", `Option ${name} is not valid for this command.`); }
function value(parsed: Parsed, name: string): string | undefined { const item = parsed.options.get(name); return typeof item === "string" ? item : undefined; }
function emit(payload: unknown, json: boolean): void { if (json || typeof payload !== "string") process.stdout.write(`${JSON.stringify(payload, null, 2)}\n`); else process.stdout.write(`${payload}\n`); }
function failure(error: unknown): number { const typed = asVibeProofError(error); process.stderr.write(`${JSON.stringify({ error: { code: typed.code, message: typed.message, details: typed.details ?? null } })}\n`); return 1; }
export async function main(argv = process.argv.slice(2)): Promise<number> { try { const parsed = parse(argv); if (parsed.options.has("--version") || parsed.positionals[0] === "version") { allow(parsed, ["--version"]); emit(VERSION, false); return 0; } if (parsed.options.has("--help") || parsed.positionals.length === 0) { allow(parsed, ["--help"]); emit(HELP.trimEnd(), false); return 0; } const command = parsed.positionals[0]!; const json = parsed.options.has("--json"); if (command === "init") { allow(parsed, ["--config", "--json"]); if (parsed.positionals.length > 2) throw new VibeProofError("VP_CLI_ARGUMENT", "init accepts at most one repository path."); emit(await initProject(parsed.positionals[1] ?? ".", value(parsed, "--config") ?? "vibeproof.config.json"), json); return 0; } if (command === "doctor") { allow(parsed, ["--config", "--browser", "--json"]); if (parsed.positionals.length > 2) throw new VibeProofError("VP_CLI_ARGUMENT", "doctor accepts at most one repository path."); const result = await doctorProject(parsed.positionals[1] ?? ".", value(parsed, "--config") ?? "vibeproof.config.json", value(parsed, "--browser")); emit(result, json); return result.ready ? 0 : 2; } if (command === "verify") { allow(parsed, ["--config", "--output", "--browser", "--keep-workspace", "--json"]); if (parsed.positionals.length > 2) throw new VibeProofError("VP_CLI_ARGUMENT", "verify accepts at most one repository path."); const outputDirectory = value(parsed, "--output"), browserExecutable = value(parsed, "--browser"); const result = await verifyProject({ source: parsed.positionals[1] ?? ".", configPath: value(parsed, "--config") ?? "vibeproof.config.json", ...(outputDirectory === undefined ? {} : { outputDirectory }), ...(browserExecutable === undefined ? {} : { browserExecutable }), ...(parsed.options.has("--keep-workspace") ? { keepWorkspace: true } : {}) }); emit({ status: result.receipt.result.status, failedStage: result.receipt.result.failedStage, commitSha: result.receipt.source.commitSha, receiptHash: result.receipt.receiptHash, outputDirectory: result.outputDirectory, ...(result.workspaceDirectory === undefined ? {} : { workspaceDirectory: result.workspaceDirectory }) }, json); return result.receipt.result.status === "verified" ? 0 : 2; } if (command === "inspect") { allow(parsed, ["--json"]); if (parsed.positionals.length !== 2) throw new VibeProofError("VP_CLI_ARGUMENT", "inspect requires exactly one receipt path."); const result = inspectReceipt(JSON.parse(await readFile(resolve(parsed.positionals[1]!), "utf8")) as unknown); emit(result, json); return result.integrity === "valid" ? 0 : 2; } throw new VibeProofError("VP_CLI_COMMAND", `Unknown command: ${command}.`); } catch (error) { return failure(error); } }
