import { access, appendFile, readFile, writeFile } from "node:fs/promises";
import { constants } from "node:fs";
import { basename, isAbsolute, join, relative, resolve, sep } from "node:path";
import { VibeProofError } from "./errors.js";
export interface InitResult { readonly created: boolean; readonly path: string; readonly reason?: "exists"; readonly gitignoreUpdated: boolean }
async function exists(path: string): Promise<boolean> { try { await access(path, constants.F_OK); return true; } catch { return false; } }
function commandFor(manager: string, script: string): string[] { if (manager === "pnpm") return ["pnpm", "run", script]; if (manager === "yarn") return ["yarn", script]; if (manager === "bun") return ["bun", "run", script]; return script === "start" ? ["npm", "start"] : ["npm", "run", script]; }
async function ensureGitignore(root: string): Promise<boolean> { const path = join(root, ".gitignore"); let current = ""; try { current = await readFile(path, "utf8"); } catch {} const entries = current.split(/\r?\n/).map((item) => item.trim()); if (entries.includes(".vibeproof/") || entries.includes(".vibeproof")) return false; await appendFile(path, `${current.length === 0 || current.endsWith("\n") ? "" : "\n"}.vibeproof/\n`, "utf8"); return true; }
export async function initProject(repoPath: string, configName = "vibeproof.config.json"): Promise<InitResult> {
  const root = resolve(repoPath); const output = isAbsolute(configName) ? resolve(configName) : resolve(root, configName); const rel = relative(root, output); if (rel === ".." || rel.startsWith(`..${sep}`) || isAbsolute(rel)) throw new VibeProofError("VP_INIT_PATH", "The generated config must remain inside the repository."); if (await exists(output)) return { created: false, path: output, reason: "exists", gitignoreUpdated: false };
  let pkg: { name?: unknown; scripts?: Record<string, unknown> }; try { pkg = JSON.parse(await readFile(join(root, "package.json"), "utf8")) as typeof pkg; } catch (error) { throw new VibeProofError("VP_INIT_PACKAGE", `Could not read package.json: ${error instanceof Error ? error.message : String(error)}.`); }
  const scripts = pkg.scripts ?? {}; const manager = await exists(join(root, "pnpm-lock.yaml")) ? "pnpm" : await exists(join(root, "yarn.lock")) ? "yarn" : await exists(join(root, "bun.lock")) || await exists(join(root, "bun.lockb")) ? "bun" : "npm"; const startScript = typeof scripts.start === "string" ? "start" : typeof scripts.dev === "string" ? "dev" : undefined; if (!startScript) throw new VibeProofError("VP_INIT_START", "package.json must define a start or dev script before VibeProof can generate a contract.");
  const install = manager === "pnpm" ? ["pnpm", "install", "--frozen-lockfile"] : manager === "yarn" ? ["yarn", "install", "--immutable"] : manager === "bun" ? ["bun", "install", "--frozen-lockfile"] : await exists(join(root, "package-lock.json")) ? ["npm", "ci"] : ["npm", "install"];
  const config = { $schema: "https://raw.githubusercontent.com/mturac/VibeProof/main/schema/vibeproof-config.schema.json", version: 1, project: { name: typeof pkg.name === "string" && pkg.name.length > 0 ? pkg.name : basename(root), root: "." }, commands: { install: { argv: install, timeoutMs: 120000 }, ...(typeof scripts.build === "string" ? { build: { argv: commandFor(manager, "build"), timeoutMs: 120000 } } : {}), start: { argv: commandFor(manager, startScript), env: { PORT: "${VIBEPROOF_PORT}" }, readyUrl: "http://127.0.0.1:${VIBEPROOF_PORT}/", readyTimeoutMs: 60000 } }, browser: { baseUrl: "http://127.0.0.1:${VIBEPROOF_PORT}", defaultTimeoutMs: 10000, journey: [{ op: "goto", path: "/" }, { op: "assertSelector", selector: "body" }, { op: "screenshot", name: "home" }] }, proof: { requireCleanClone: true, requireBuild: typeof scripts.build === "string", requireBrowser: true, requireRestart: false }, output: { keepWorkspaceOnFailure: true, keepWorkspaceOnSuccess: false } };
  await writeFile(output, `${JSON.stringify(config, null, 2)}\n`, { encoding: "utf8", flag: "wx" }); return { created: true, path: output, gitignoreUpdated: await ensureGitignore(root) };
}
