import { readdir, readFile, stat } from "node:fs/promises";
import { extname, join, relative, sep } from "node:path";
import { hashCanonical, sha256 } from "./canonical.js";
import { VibeProofError } from "./errors.js";
import type { ArtifactReceipt, VibeProofReceipt } from "./types.js";
const DERIVED = new Set(["receipt.json", "report.md", "report.html"]);
function mediaType(path: string): string { switch (extname(path).toLowerCase()) { case ".json": return "application/json"; case ".html": return "text/html"; case ".md": return "text/markdown"; case ".png": return "image/png"; case ".log": return "text/plain"; default: return "application/octet-stream"; } }
async function files(root: string, current = root): Promise<string[]> { const result: string[] = []; for (const entry of await readdir(current, { withFileTypes: true })) { const path = join(current, entry.name); if (entry.isDirectory()) result.push(...await files(root, path)); else if (entry.isFile()) result.push(path); } return result; }
export async function collectArtifacts(root: string, excluded: ReadonlySet<string> = new Set()): Promise<ArtifactReceipt[]> { const result: ArtifactReceipt[] = []; for (const path of (await files(root)).sort()) { const portable = relative(root, path).split(sep).join("/"); if (excluded.has(portable)) continue; const bytes = await readFile(path); const info = await stat(path); result.push({ path: portable, mediaType: mediaType(portable), bytes: info.size, sha256: sha256(bytes) }); } return result; }
export async function collectEvidenceArtifacts(root: string): Promise<ArtifactReceipt[]> { return await collectArtifacts(root, DERIVED); }
export function sealReceipt(input: Omit<VibeProofReceipt, "receiptHash">): VibeProofReceipt { return { ...input, receiptHash: hashCanonical(input) }; }
export function createRunId(commitSha: string, timestamp = Date.now()): string { return `${timestamp}-${commitSha.slice(0, 8)}`; }
export function portableSource(value: string): string { const scp = value.match(/^(?:[^@\s]+@)?([^:\s]+):(.+)$/); if (scp !== null && !value.includes("://")) return `ssh://${scp[1]!}/${scp[2]!.replace(/^\/+/, "")}`; try { const url = new URL(value); if (url.protocol === "file:") return `local:${url.pathname.split("/").filter(Boolean).at(-1) ?? "repository"}`; url.username = ""; url.password = ""; return url.toString().replace(/\/$/, ""); } catch { const normalized = value.replaceAll("\\", "/").replace(/\/$/, ""); return `local:${normalized.split("/").filter(Boolean).at(-1) ?? "repository"}`; } }
export interface ReceiptInspection { readonly integrity: "valid" | "invalid"; readonly status: "verified" | "failed" | "unknown"; readonly projectName: string; readonly commitSha: string; readonly receiptHash: string; readonly failedStage: string | null }
export function inspectReceipt(value: unknown): ReceiptInspection { if (value === null || typeof value !== "object" || Array.isArray(value)) throw new VibeProofError("VP_RECEIPT_TYPE", "Receipt must be an object."); const receipt = value as Record<string, unknown>; const actual = typeof receipt.receiptHash === "string" ? receipt.receiptHash : ""; const copy = { ...receipt }; delete copy.receiptHash; const result = receipt.result !== null && typeof receipt.result === "object" ? receipt.result as Record<string, unknown> : {}; const source = receipt.source !== null && typeof receipt.source === "object" ? receipt.source as Record<string, unknown> : {}; return { integrity: actual.length === 64 && actual === hashCanonical(copy) ? "valid" : "invalid", status: result.status === "verified" || result.status === "failed" ? result.status : "unknown", projectName: typeof receipt.projectName === "string" ? receipt.projectName : "unknown", commitSha: typeof source.commitSha === "string" ? source.commitSha : "unknown", receiptHash: actual, failedStage: typeof result.failedStage === "string" ? result.failedStage : null }; }
