import { spawn } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { createRedactor } from "./command.js";
import { expandVariables } from "./config.js";
import { VibeProofError } from "./errors.js";
import type { CommandSpec } from "./types.js";
export interface ManagedApplicationOptions { readonly spec: CommandSpec & { readonly readyUrl: string }; readonly cwd: string; readonly variables: Readonly<Record<string, string>>; readonly inheritedEnvironment: readonly string[]; readonly redactPatterns: readonly string[]; readonly maxLogBytes: number; readonly logsDirectory: string }
function bounded(value: string, maxBytes: number): string { const buffer = Buffer.from(value, "utf8"); if (buffer.length <= maxBytes) return value; const marker = `\n...[truncated ${buffer.length - maxBytes} bytes]`; return buffer.subarray(0, Math.max(0, maxBytes - Buffer.byteLength(marker))).toString("utf8") + marker; }
function environment(options: ManagedApplicationOptions): NodeJS.ProcessEnv { const result: NodeJS.ProcessEnv = {}; for (const key of options.inheritedEnvironment) { const value = process.env[key]; if (value !== undefined) result[key] = value; } for (const [key, value] of Object.entries(options.spec.env ?? {})) result[key] = expandVariables(value, options.variables); result.VIBEPROOF = "1"; return result; }
async function terminate(child: any): Promise<void> { if (child.exitCode !== null || child.signalCode !== null) return; try { process.kill(process.platform === "win32" ? child.pid : -child.pid, "SIGTERM"); } catch {} await Promise.race([new Promise<void>((r) => child.once("close", () => r())), new Promise<void>((r) => setTimeout(r, 1500))]); if (child.exitCode === null) { try { process.kill(process.platform === "win32" ? child.pid : -child.pid, "SIGKILL"); } catch {} await Promise.race([new Promise<void>((r) => child.once("close", () => r())), new Promise<void>((r) => setTimeout(r, 500))]); } }
async function ready(url: string, child: any, timeoutMs: number): Promise<void> { const deadline = Date.now() + timeoutMs; let last = "not ready"; while (Date.now() < deadline) { if (child.exitCode !== null) throw new VibeProofError("VP_RUNTIME_EXITED", `Application exited before readiness with code ${child.exitCode}.`); try { const response = await fetch(url, { redirect: "manual", signal: AbortSignal.timeout(750) }); if (response.status >= 200 && response.status < 400) return; last = `HTTP ${response.status}`; } catch (error) { last = error instanceof Error ? error.message : String(error); } await new Promise((r) => setTimeout(r, 75)); } throw new VibeProofError("VP_RUNTIME_TIMEOUT", `Application did not become ready at ${url}: ${last}.`); }
export class ManagedApplication {
  readonly #options: ManagedApplicationOptions; #child: any | undefined; #stdout = ""; #stderr = ""; #generation = 0; #startedAt = "";
  constructor(options: ManagedApplicationOptions) { this.#options = options; }
  get running(): boolean { return this.#child !== undefined && this.#child.exitCode === null; }
  async start(): Promise<{ generation: number; readyUrl: string; logPath: string }> { if (this.running) throw new VibeProofError("VP_RUNTIME_STATE", "Application is already running."); this.#generation += 1; this.#stdout = ""; this.#stderr = ""; this.#startedAt = new Date().toISOString(); const argv = this.#options.spec.argv.map((value) => expandVariables(value, this.#options.variables)); const cwd = resolve(this.#options.cwd, this.#options.spec.cwd ?? "."); const child = spawn(argv[0]!, argv.slice(1), { cwd, env: environment(this.#options), shell: false, detached: true, stdio: ["ignore", "pipe", "pipe"] }); this.#child = child; child.stdout?.setEncoding("utf8"); child.stderr?.setEncoding("utf8"); child.stdout?.on("data", (chunk: string) => { if (Buffer.byteLength(this.#stdout) < this.#options.maxLogBytes * 2) this.#stdout += chunk; }); child.stderr?.on("data", (chunk: string) => { if (Buffer.byteLength(this.#stderr) < this.#options.maxLogBytes * 2) this.#stderr += chunk; }); await new Promise<void>((resolveStart, reject) => { const timer = setTimeout(resolveStart, 25); child.once("error", (error: Error) => { clearTimeout(timer); reject(new VibeProofError("VP_RUNTIME_SPAWN", `Failed to start application: ${error.message}.`)); }); }); const readyUrl = expandVariables(this.#options.spec.readyUrl, this.#options.variables); try { await ready(readyUrl, child, this.#options.spec.readyTimeoutMs ?? 60_000); } catch (error) { await this.stop(); throw error; } return { generation: this.#generation, readyUrl, logPath: join(this.#options.logsDirectory, `start-${this.#generation}.log`) }; }
  async stop(): Promise<void> { const child = this.#child; if (child === undefined) return; await terminate(child); await mkdir(this.#options.logsDirectory, { recursive: true }); const redact = createRedactor(this.#options.redactPatterns); const output = [`generation=${this.#generation}`, `startedAt=${this.#startedAt}`, `finishedAt=${new Date().toISOString()}`, "", "[stdout]", bounded(redact(this.#stdout), this.#options.maxLogBytes), "", "[stderr]", bounded(redact(this.#stderr), this.#options.maxLogBytes)].join("\n"); await writeFile(join(this.#options.logsDirectory, `start-${this.#generation}.log`), output, "utf8"); this.#child = undefined; }
  async restart(): Promise<{ generation: number; readyUrl: string; logPath: string }> { await this.stop(); return await this.start(); }
}
