import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, isAbsolute, join, resolve } from "node:path";
import { runBrowserJourney } from "./browser.js";
import { createRedactor, runCommand } from "./command.js";
import { expandVariables, parseConfig } from "./config.js";
import { VibeProofError, asVibeProofError } from "./errors.js";
import { cloneRepository, inspectRepository } from "./git.js";
import { findFreePort } from "./network.js";
import { collectEvidenceArtifacts, createRunId, portableSource, sealReceipt } from "./receipt.js";
import { renderHtml, renderMarkdown } from "./report.js";
import { ManagedApplication } from "./service.js";
import type { BrowserStepResult, CommandSpec, ProofStage, ProofStageName, VerificationResult, VerifyOptions, VibeProofConfig, VibeProofReceipt } from "./types.js";
function now(): string { return new Date().toISOString(); }
function stage(name: ProofStageName, required: boolean, status: ProofStage["status"], evidence: readonly string[] = [], error?: VibeProofError, startedAt?: string): ProofStage { const finishedAt = now(); return { name, required, status, ...(startedAt === undefined ? {} : { startedAt, finishedAt, durationMs: Math.max(0, Date.parse(finishedAt) - Date.parse(startedAt)) }), evidence, ...(error === undefined ? {} : { error: { code: error.code, message: error.message } }) }; }
function partialSteps(error: VibeProofError): BrowserStepResult[] { return Array.isArray(error.details?.results) ? error.details!.results as BrowserStepResult[] : []; }
function context(config: VibeProofConfig, cwd: string, variables: Readonly<Record<string, string>>, logPath: string) { return { cwd, inheritedEnvironment: config.security.inheritEnv, variables, redactPatterns: config.security.redactPatterns, maxLogBytes: config.security.maxLogBytes, logPath }; }
function looksRemote(value: string): boolean { return /^(?:https?|ssh|git):/i.test(value) || /^[^@\s]+@[^:\s]+:.+/.test(value); }
function sanitizeContract(config: VibeProofConfig): unknown { const redact = createRedactor(config.security.redactPatterns); const command = (spec: CommandSpec | undefined): unknown => spec === undefined ? undefined : { ...spec, argv: spec.argv.map(redact), ...(spec.env === undefined ? {} : { env: Object.fromEntries(Object.keys(spec.env).sort().map((key) => [key, "[REDACTED]"])) }), ...(spec.readyUrl === undefined ? {} : { readyUrl: redact(spec.readyUrl) }) }; const scrub = (item: VibeProofConfig["browser"]["journey"][number]): unknown => Object.fromEntries(Object.entries(item).map(([key, value]) => [key, key === "text" || key === "value" ? "[REDACTED]" : typeof value === "string" ? redact(value) : value])); return { ...config, commands: { ...(config.commands.install === undefined ? {} : { install: command(config.commands.install) }), ...(config.commands.build === undefined ? {} : { build: command(config.commands.build) }), start: command(config.commands.start) }, browser: { ...config.browser, baseUrl: redact(config.browser.baseUrl), journey: config.browser.journey.map(scrub), ...(config.browser.afterRestart === undefined ? {} : { afterRestart: config.browser.afterRestart.map(scrub) }) } }; }
function blocked(name: ProofStageName, required: boolean, by: ProofStageName): ProofStage { return stage(name, required, "skipped", [`blocked-by=${by}`]); }
async function buildStage(name: "install" | "build", spec: CommandSpec, config: VibeProofConfig, cwd: string, variables: Readonly<Record<string, string>>, output: string): Promise<{ item: ProofStage; passed: boolean }> { const startedAt = now(); const log = `logs/${name}.log`; try { const result = await runCommand(spec, context(config, cwd, variables, join(output, log))); const passed = result.exitCode === 0 && !result.timedOut; if (passed) return { item: stage(name, true, "passed", [`exit=${result.exitCode}`, `log=${log}`], undefined, startedAt), passed }; const reason = result.timedOut ? `${name} timed out.` : result.stderr.trim() || `${name} exited ${result.exitCode}.`; return { item: stage(name, true, "failed", [`exit=${String(result.exitCode)}`, `timedOut=${String(result.timedOut)}`, `log=${log}`], new VibeProofError(`VP_${name.toUpperCase()}_FAILED`, reason), startedAt), passed: false }; } catch (error) { return { item: stage(name, true, "failed", [`log=${log}`], asVibeProofError(error, `VP_${name.toUpperCase()}_FAILED`), startedAt), passed: false }; } }
export async function verifyProject(options: VerifyOptions): Promise<VerificationResult> {
  if (process.platform === "win32") throw new VibeProofError("VP_PLATFORM_BLOCKED", "VibeProof v0.1 supports macOS and Linux only.");
  if (looksRemote(options.source)) throw new VibeProofError("VP_REMOTE_SOURCE_UNSUPPORTED", "VibeProof v0.1 verifies local Git repositories. Clone the repository locally and pass its path.");
  const sourceInput = resolve(options.source); const configPath = isAbsolute(options.configPath) ? options.configPath : join(sourceInput, options.configPath); let raw: unknown; try { raw = JSON.parse(await readFile(configPath, "utf8")) as unknown; } catch (error) { throw new VibeProofError("VP_CONFIG_READ", `Could not read ${configPath}: ${error instanceof Error ? error.message : String(error)}.`); }
  const config = parseConfig(raw); const sourceIdentity = await inspectRepository(sourceInput); if (config.proof.requireCleanClone && !sourceIdentity.clean) throw new VibeProofError("VP_SOURCE_DIRTY", "Source repository has tracked or untracked changes; commit or ignore them before proof.");
  const runId = createRunId(sourceIdentity.commitSha); const outputDirectory = resolve(options.outputDirectory ?? join(sourceIdentity.root, ".vibeproof", runId)); await mkdir(join(outputDirectory, "logs"), { recursive: true }); await mkdir(join(outputDirectory, "screenshots"), { recursive: true }); await writeFile(join(outputDirectory, "contract.snapshot.json"), `${JSON.stringify(sanitizeContract(config), null, 2)}\n`, "utf8");
  const workspaceParent = await mkdtemp(join(tmpdir(), "vibeproof-run-")); const workspace = join(workspaceParent, "repo"); const stages: ProofStage[] = []; let journey: BrowserStepResult[] = [], afterRestart: BrowserStepResult[] = []; let browserExecutable: string | undefined, browserVersion: string | undefined; let runtimeReady = false, browserPassed = false; let restartPassed: boolean | null = config.proof.requireRestart ? false : null; let installPassed: boolean | null = config.commands.install === undefined ? null : false; let buildPassed: boolean | null = config.commands.build === undefined ? null : false; let cloneCommit = ""; let app: ManagedApplication | undefined; let failedStage: ProofStageName | null = null; const ref = config.project.ref ?? sourceIdentity.commitSha; const port = await findFreePort(); const variables = { VIBEPROOF_PORT: String(port), VIBEPROOF_WORKSPACE: workspace };
  try {
    const sourceStarted = now(); try { const clone = await cloneRepository({ source: sourceIdentity.root, ref, destination: workspace }); cloneCommit = clone.commitSha; if (!clone.clean) throw new VibeProofError("VP_CLONE_DIRTY", "The reconstructed clone is not clean."); stages.push(stage("source", true, "passed", [`commit=${clone.commitSha}`, "clean-clone=true"], undefined, sourceStarted)); } catch (error) { stages.push(stage("source", true, "failed", [], asVibeProofError(error, "VP_SOURCE_PROOF"), sourceStarted)); failedStage = "source"; }
    const projectRoot = join(workspace, config.project.root);
    if (!config.commands.install) stages.push(stage("install", false, "skipped", ["not-declared"])); else if (failedStage) stages.push(blocked("install", true, failedStage)); else { const result = await buildStage("install", config.commands.install, config, projectRoot, variables, outputDirectory); stages.push(result.item); installPassed = result.passed; if (!result.passed) failedStage = "install"; }
    if (!config.commands.build) stages.push(stage("build", config.proof.requireBuild, "skipped", ["not-declared"])); else if (failedStage) stages.push(blocked("build", true, failedStage)); else { const result = await buildStage("build", config.commands.build, config, projectRoot, variables, outputDirectory); stages.push(result.item); buildPassed = result.passed; if (!result.passed) failedStage = "build"; }
    if (failedStage) stages.push(blocked("runtime", true, failedStage)); else { const startedAt = now(); app = new ManagedApplication({ spec: config.commands.start, cwd: projectRoot, variables, inheritedEnvironment: config.security.inheritEnv, redactPatterns: config.security.redactPatterns, maxLogBytes: config.security.maxLogBytes, logsDirectory: join(outputDirectory, "logs") }); try { const started = await app.start(); runtimeReady = true; stages.push(stage("runtime", true, "passed", [`ready=${started.readyUrl}`, `generation=${started.generation}`, `log=logs/start-${started.generation}.log`], undefined, startedAt)); } catch (error) { stages.push(stage("runtime", true, "failed", [], asVibeProofError(error, "VP_RUNTIME_FAILED"), startedAt)); failedStage = "runtime"; } }
    if (!config.proof.requireBrowser) stages.push(stage("browser", false, "skipped", ["disabled-by-contract"])); else if (failedStage) stages.push(blocked("browser", true, failedStage)); else { const startedAt = now(); try { const result = await runBrowserJourney({ baseUrl: expandVariables(config.browser.baseUrl, variables), steps: config.browser.journey, screenshotsDirectory: join(outputDirectory, "screenshots"), defaultTimeoutMs: config.browser.defaultTimeoutMs, ...((options.browserExecutable ?? config.browser.executable) === undefined ? {} : { executable: options.browserExecutable ?? config.browser.executable }) }); journey = [...result.steps]; browserExecutable = result.browserExecutable; browserVersion = result.browserVersion; browserPassed = true; stages.push(stage("browser", true, "passed", [`steps=${journey.length}`], undefined, startedAt)); } catch (error) { const typed = asVibeProofError(error, "VP_BROWSER_FAILED"); journey = partialSteps(typed); stages.push(stage("browser", true, "failed", [`steps=${journey.length}`], typed, startedAt)); failedStage = "browser"; } }
    if (!config.proof.requireRestart) stages.push(stage("restart", false, "skipped", ["disabled-by-contract"])); else if (failedStage) stages.push(blocked("restart", true, failedStage)); else { const startedAt = now(); try { if (!app) throw new VibeProofError("VP_RESTART_STATE", "Application process is unavailable for restart."); const restarted = await app.restart(); const result = await runBrowserJourney({ baseUrl: expandVariables(config.browser.baseUrl, variables), steps: config.browser.afterRestart ?? [], screenshotsDirectory: join(outputDirectory, "screenshots"), defaultTimeoutMs: config.browser.defaultTimeoutMs, ...((options.browserExecutable ?? config.browser.executable) === undefined ? {} : { executable: options.browserExecutable ?? config.browser.executable }) }); afterRestart = [...result.steps]; browserExecutable ??= result.browserExecutable; browserVersion ??= result.browserVersion; restartPassed = true; stages.push(stage("restart", true, "passed", [`generation=${restarted.generation}`, `steps=${afterRestart.length}`, `log=logs/start-${restarted.generation}.log`], undefined, startedAt)); } catch (error) { const typed = asVibeProofError(error, "VP_RESTART_FAILED"); afterRestart = partialSteps(typed); restartPassed = false; stages.push(stage("restart", true, "failed", [`steps=${afterRestart.length}`], typed, startedAt)); failedStage = "restart"; } }
  } finally { await app?.stop().catch(() => undefined); }
  const verified = failedStage === null && runtimeReady && (!config.proof.requireBrowser || browserPassed) && (!config.proof.requireRestart || restartPassed === true); const draft: Omit<VibeProofReceipt, "receiptHash"> = { receiptVersion: 1, runId, projectName: config.project.name, createdAt: now(), source: { requested: portableSource(sourceIdentity.root), requestedRef: ref, commitSha: cloneCommit || sourceIdentity.commitSha, cleanClone: stages.find((item) => item.name === "source")?.status === "passed", projectRoot: config.project.root }, environment: { platform: process.platform, architecture: process.arch, nodeVersion: process.version, ...(browserExecutable === undefined ? {} : { browserExecutable: basename(browserExecutable) }), ...(browserVersion === undefined ? {} : { browserVersion }) }, stages, browser: { journey, afterRestart }, artifacts: await collectEvidenceArtifacts(outputDirectory), claims: { sourceVerified: stages.find((item) => item.name === "source")?.status === "passed", installPassed, buildPassed, runtimeReady, browserJourneyPassed: browserPassed, restartPassed, verified }, result: { status: verified ? "verified" : "failed", failedStage } }; const receipt = sealReceipt(draft); await writeFile(join(outputDirectory, "receipt.json"), `${JSON.stringify(receipt, null, 2)}\n`, "utf8"); await writeFile(join(outputDirectory, "report.md"), renderMarkdown(receipt), "utf8"); await writeFile(join(outputDirectory, "report.html"), renderHtml(receipt), "utf8"); const keep = options.keepWorkspace ?? (verified ? config.output.keepWorkspaceOnSuccess : config.output.keepWorkspaceOnFailure); if (!keep) await rm(workspaceParent, { recursive: true, force: true }); return { receipt, outputDirectory, ...(keep ? { workspaceDirectory: workspace } : {}) };
}
